import PrimaryLayout from 'components/layouts/PrimaryLayout'
import Head from 'next/head'

import { NextPageWithLayout } from './page'

const Home: NextPageWithLayout = () => (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <section>this is page content</section>
    </>
)

Home.getLayout = (page) => {
    return <PrimaryLayout>{page}</PrimaryLayout>
}

export default Home
